# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computer sparse cannonical correlation vectors
#' 
#' @param X1 Matrix of covariates.
#' @param X2 Matrix of covariates.
#' @param l1 Penalisation term.
#' @param l2 Penalisation term.
#' @param niter Number of iterations to run algorithm for (default = 1000).
#' @param threshold Stopping criterea threshold (default = 1e-6).
#' 
#' @export sCCA
sCCA <- function(X1, X2, l1, l2, niter = 1000L, threshold = 1.0e-6) {
    .Call(`_rcca_sCCA`, X1, X2, l1, l2, niter, threshold)
}

#' Computer sparse cannonical correlation vectors via Suo 2017 method
#' 
#' @param X1 Matrix of covariates.
#' @param X2 Matrix of covariates.
#' @param l1 Penalisation term.
#' @param l2 Penalisation term.
#' @param niter Number of iterations to run algorithm for (default = 1000).
#' @param threshold Stopping criterea threshold (default = 1e-6).
#' @param verbose Print debug information.
#' 
#' @export
rCCA <- function(X1, X2, l1, l2, niter = 1000L, threshold = 1.0e-6, verbose = TRUE) {
    .Call(`_rcca_rCCA`, X1, X2, l1, l2, niter, threshold, verbose)
}

rCCA_opt <- function(X, w, c, mu, lambda, l, niter, threshold) {
    .Call(`_rcca_rCCA_opt`, X, w, c, mu, lambda, l, niter, threshold)
}

binary_search <- function(v, l, niter, threshold) {
    .Call(`_rcca_binary_search`, v, l, niter, threshold)
}

soft_threshold <- function(v, d) {
    .Call(`_rcca_soft_threshold`, v, d)
}

