# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cca <- function(X1, X2, l1, l2, niter, threshold, verbose) {
    .Call(`_rcca_cca`, X1, X2, l1, l2, niter, threshold, verbose)
}

cca_opt <- function(X, w, c, mu, lambda, l, niter, threshold) {
    .Call(`_rcca_cca_opt`, X, w, c, mu, lambda, l, niter, threshold)
}

#' @export
cca_permutation_validation <- function(X1, X2, l1, l2, permutations, niter, threshold, verbose) {
    .Call(`_rcca_cca_permutation_validation`, X1, X2, l1, l2, permutations, niter, threshold, verbose)
}

soft_threshold <- function(v, d) {
    .Call(`_rcca_soft_threshold`, v, d)
}

