# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sCCA_ <- function(X1, X2, l1, l2, w2, niter, threshold) {
    .Call(`_rcca_sCCA_`, X1, X2, l1, l2, w2, niter, threshold)
}

rCCA_ <- function(X1, X2, l1, l2, niter, threshold, verbose) {
    .Call(`_rcca_rCCA_`, X1, X2, l1, l2, niter, threshold, verbose)
}

rCCA_opt <- function(X, w, c, mu, lambda, l, niter, threshold) {
    .Call(`_rcca_rCCA_opt`, X, w, c, mu, lambda, l, niter, threshold)
}

#' @export
rCCA_permutation_validation <- function(X1, X2, l1, l2, permutations, niter, threshold, verbose, threads) {
    .Call(`_rcca_rCCA_permutation_validation`, X1, X2, l1, l2, permutations, niter, threshold, verbose, threads)
}

binary_search <- function(v, l, niter, threshold) {
    .Call(`_rcca_binary_search`, v, l, niter, threshold)
}

soft_threshold <- function(v, d) {
    .Call(`_rcca_soft_threshold`, v, d)
}

